---
- name: Disable firewalld
  ansible.builtin.systemd:
    state: stopped
    name: firewalld
    enabled: false

- name: Disable selinux
  ansible.posix.selinux:
    state: disabled

- name: Create custom fact directory
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    mode: "0755"
