---
- name: Copy rabbitmq env file
  ansible.builtin.template:
    src: rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf
    owner: rabbitmq
    group: rabbitmq
    mode: "0644"
  notify:
    - restart rabbitmq-server service

- name: Copy rabbitmq plugins file
  ansible.builtin.template:
    src: enabled_plugins.j2
    dest: /etc/rabbitmq/enabled_plugins
    owner: rabbitmq
    group: rabbitmq
    mode: "0644"
  notify:
    - restart rabbitmq-server service

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
