---
- name: Setup Redis repo
  ansible.builtin.yum_repository:
    name: "redis"
    description: Official Redis repo
    baseurl: "http://packages.redis.io/rpm/rhel{{ ansible_distribution_major_version }}"
    gpgcheck: false
    enabled: true
  when: not use_local_repo

- name: Setup Alma repo for compat-openssl10
  ansible.builtin.yum_repository:
    name: "alma8-10"
    description: AlmaLinux 8.10 repo
    baseurl: "https://repo.almalinux.org/almalinux/8.10/AppStream/x86_64/os/"
    gpgcheck: false
    enabled: true
  when: not use_local_repo

- name: Install Redis Stack packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    update_cache: true
    disablerepo: "{{ use_local_repo | ternary('*', '') }}"
    enablerepo: "{{ use_local_repo | ternary('sp-local-' +
      (ansible_distribution | lower + ansible_distribution_major_version), 'redis') }}"
  loop: "{{ redis_stack_packages.redhat }}"

- name: Notify that packages are installed successfully
  ansible.builtin.debug:
    msg: Packages for Redis Stack are installed successfully for node {{ ansible_host
      }}
