---
- name: Include install tasks
  ansible.builtin.include_tasks:
    "{{ ansible_distribution_file_variety | lower }}/{{
    redis_stack_install_type }}/06-install.yaml"
  when: '"install" in redis_stack_steps'

- name: Include configure tasks
  ansible.builtin.include_tasks:
    "{{ ansible_distribution_file_variety | lower }}/{{
    redis_stack_install_type }}/09-configure.yaml"
  when: '"configure" in redis_stack_steps'

- name: Include post_check tasks
  ansible.builtin.include_tasks:
    "{{ ansible_distribution_file_variety | lower }}/{{
    redis_stack_install_type }}/15-post_check.yaml"
  when: '"post_check" in redis_stack_steps'
